@url = http://localhost:1106/api/

### list players
get {{url}}nba/roster

### get player
get {{url}}nba/roster/?playerId=13

### Delete player
DELETE {{url}}nba/roster?playerId=9000015

### Create new player
POST {{url}}nba/roster
Content-Type: application/json

{
    "playerId": "0",
    "teamCode": "DET",
    "firstName": "Fred",
    "lastName": "Flintstone",
    "position": "F",
    "number": "74",
    "height": "76",
    "weight": "315",
    "dateOfBirth": "2001-07-21T00:00:00",
    "birthCityState": "Media, PA",
    "birthCountry" : "United States",
    "college": "Illinois",
    "draftYear": 2021,
    "seasonYear" : 2025,
    "pointsPerGame" : 11,
    "reboundsPerGame" : 2.3,
    "assistsPerGame" : 5.6
}


### Update NBA player
PUT {{url}}nba/roster
Content-Type: application/json

{
    "playerId": "9000026",
    "teamCode": "DET",
    "firstName": "Barny",
    "lastName": "Rubble",
    "position": "F",
    "number": "74",
    "height": "76",
    "weight": "315",
    "dateOfBirth": "2001-07-21T00:00:00",
    "birthCityState": "Media, PA",
    "birthCountry" : "United States",
    "college": "Illinois",
    "draftYear": 2021,
    "seasonYear" : 2025,
    "pointsPerGame" : 18,
    "reboundsPerGame" : 7.3,
    "assistsPerGame" : 5.9
}


### Update NBA player (Fail)
PUT {{url}}nba/roster
Content-Type: application/json

{
  "playerId": 5,
  "Height": "6' 5\""
}

### Update NBA player that doesn't exist
PUT {{url}}nba/roster
Content-Type: application/json

{
  "playerId": 9990211,
  "FirstName": "Maxi",
  "LastName": "Mouse"
}