@url = http://localhost:1106/api/v2/

### get all roster
get {{url}}nfl/roster

### get player by playerId
get {{url}}nfl/roster/?playerId=102177

### create new player
post {{url}}nfl/roster
Content-Type: application/json

{
    "playerId": "0",
    "teamCode": "ARI",
    "firstName": "Isaiah",
    "lastName": "Adams",
    "position": "G",
    "number": "74",
    "height": "76",
    "weight": "315",
    "dateOfBirth": "2001-07-21T00:00:00",
    "birthCityState": "Media, PA",
    "birthCountry" : "United States",
    "college": "Illinois",
    "draftYear": 2021,
    "seasonYear" : 2025,
    "sacks": 8,
    "touchdowns": 3
}

### update player by playerId
put {{url}}nfl/roster
Content-Type: application/json

{
    "playerId": "9000009",
    "teamCode": "ARI",
    "firstName": "Isaiah",
    "lastName": "Adams",
    "position": "G",
    "number": "74",
    "height": "76",
    "weight": "315",
    "dateOfBirth": "2001-07-21T00:00:00",
    "birthCityState": "Media, PA",
    "birthCountry" : "United States",
    "college": "Illinois",
    "draftYear": 2021,
    "seasonYear" : 2025,
    "sacks": 9,
    "touchdowns": 4
}

### delete player by playerId
delete {{url}}nfl/roster/?playerId=9000008

### update a player that doesn't exist
put {{url}}nfl/roster
Content-Type: application/json

{
    "teamCode": "ARI",
    "firstName": "Isaiah",
    "lastName": "Adams",
    "position": "G",
    "number": "74",
    "height": "76",
    "weight": "315",
    "dateOfBirth": "2001-07-21T00:00:00",
    "birthCityState": "Media, PA",
    "birthCountry" : "United States",
    "college": "Illinois",
    "draftYear": 2021,
    "seasonYear" : 2025

}