@url = http://localhost:1106/api/v2/

### list players
get {{url}}nhl/roster

## get player
### list players
get {{url}}nhl/roster/?playerId=518

### Delete NHL player
DELETE {{url}}nhl/roster?playerId=518

### Create new NHL player
POST {{url}}nhl/roster
Content-Type: application/json

{
    "playerId": "0",
    "teamCode": "WSH",
    "firstName": "Fred",
    "lastName": "Flintstone",
    "position": "F",
    "number": "74",
    "height": "76",
    "weight": "315",
    "dateOfBirth": "2001-07-21T00:00:00",
    "birthCityState": "Media, PA",
    "birthCountry" : "United States",
    "college": "Illinois",
    "draftYear": 2021,
    "seasonYear" : 2025,
    "handed" : "R",
    "goals" : 3,
    "penaltyMinutes": 95,
    "points" : 44,
    "savePct" : 0
}


### Update NHL player
PUT {{url}}nhl/roster
Content-Type: application/json

{
    "playerId": "9000031",
    "teamCode": "WSH",
    "firstName": "Barny",
    "lastName": "Flintstone",
    "position": "F",
    "number": "74",
    "height": "76",
    "weight": "315",
    "dateOfBirth": "2001-07-21T00:00:00",
    "birthCityState": "Media, PA",
    "birthCountry" : "United States",
    "college": "Illinois",
    "draftYear": 2020,
    "seasonYear" : 2025,
    "handed" : "L",
    "goals" : 3,
    "penaltyMinutes": 123,
    "points" : 24,
    "savePct" : 0.43
}

### Attempt update to a player that doesn't exist
PUT {{url}}nhl/roster
Content-Type: application/json

{
  "playerId": 999901,
  "name": "JD Grier",
  "team": "Bruins",
  "number": "13",
  "position": "LW",
  "handed": "B",
  "age": 33,
  "draftYear": 2011,
  "seasonYear": 2025,
  "birthCityState": "nowhere",
  "birthCountry": "noplace"
}
