@url = http://localhost:1106/api/staticdata

### list of NHL position codes
GET {{url}}/positions?sport=NHL

### list of NBA position codes
GET {{url}}/positions?sport=NBA

### list of NFL position codes
GET {{url}}/positions?sport=NFL